FROM public.ecr.aws/w3i8r4e2/inqdo-tools:latest

# Copy function code
COPY . ${LAMBDA_TASK_ROOT}

COPY ./requirements-prd.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements-prd.txt

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "main.handler" ]
